#!/bin/sh
#python launch.py --remoteDir="L2res" --cfg=../L2res_cfg.py --unitsPerJob=2 --production_label="V8" -o data JetHT_Run2016B_03Feb2017_v2
#python launch.py --remoteDir="L2res" --cfg=../L2res_cfg.py --unitsPerJob=2 --production_label="V8" -o data JetHT_Run2016C_03Feb2017
#python launch.py --remoteDir="L2res" --cfg=../L2res_cfg.py --unitsPerJob=2 --production_label="V8" -o data JetHT_Run2016D_03Feb2017
#python launch.py --remoteDir="L2res" --cfg=../L2res_cfg.py --unitsPerJob=2 --production_label="V8" -o data JetHT_Run2016E_03Feb2017
#python launch.py --remoteDir="L2res" --cfg=../L2res_cfg.py --unitsPerJob=2 --production_label="V8" -o data JetHT_Run2016F_03Feb2017
#python launch.py --remoteDir="L2res" --cfg=../L2res_cfg.py --unitsPerJob=2 --production_label="V8" -o data JetHT_Run2016G_03Feb2017
#python launch.py --remoteDir="L2res" --cfg=../L2res_cfg.py --unitsPerJob=2 --production_label="V8" -o data JetHT_Run2016H_03Feb2017_v2
#python launch.py --remoteDir="L2res" --cfg=../L2res_cfg.py --unitsPerJob=2 --production_label="V8" -o data JetHT_Run2016H_03Feb2017_v3
python launch.py --remoteDir="L2res" --cfg=../L2res_cfg.py --unitsPerJob=2 --production_label="V8" -o data JetHT_Run2016B_18Apr2017
python launch.py --remoteDir="L2res" --cfg=../L2res_cfg.py --unitsPerJob=2 --production_label="V8" -o data JetHT_Run2016C_18Apr2017
python launch.py --remoteDir="L2res" --cfg=../L2res_cfg.py --unitsPerJob=2 --production_label="V8" -o data JetHT_Run2016D_18Apr2017
python launch.py --remoteDir="L2res" --cfg=../L2res_cfg.py --unitsPerJob=2 --production_label="V8" -o data JetHT_Run2016E_18Apr2017
python launch.py --remoteDir="L2res" --cfg=../L2res_cfg.py --unitsPerJob=2 --production_label="V8" -o data JetHT_Run2016F_18Apr2017
python launch.py --remoteDir="L2res" --cfg=../L2res_cfg.py --unitsPerJob=2 --production_label="V8" -o data JetHT_Run2016G_18Apr2017
python launch.py --remoteDir="L2res" --cfg=../L2res_cfg.py --unitsPerJob=2 --production_label="V8" -o data JetHT_Run2016H_18Apr2017

#python launch.py --remoteDir="chsDoctor" --cfg=../chsDoctor_cfg.py --unitsPerJob=1 --production_label="V10" -o mc QCD_flat
#python launch.py --remoteDir="chsDoctor" --cfg=../chsDoctor_cfg.py --unitsPerJob=1 --production_label="V10" -o mc QCD_flat_noPU

python launch.py --remoteDir="L2res" --cfg=../L2res_cfg.py --unitsPerJob=2 --production_label="V8" -o mc QCD_Pt50to80
python launch.py --remoteDir="L2res" --cfg=../L2res_cfg.py --unitsPerJob=2 --production_label="V8" -o mc QCD_Pt80to120
python launch.py --remoteDir="L2res" --cfg=../L2res_cfg.py --unitsPerJob=2 --production_label="V8" -o mc QCD_Pt80to120_ext2
python launch.py --remoteDir="L2res" --cfg=../L2res_cfg.py --unitsPerJob=2 --production_label="V8" -o mc QCD_Pt120to170
python launch.py --remoteDir="L2res" --cfg=../L2res_cfg.py --unitsPerJob=2 --production_label="V8" -o mc QCD_Pt120to170_ext
python launch.py --remoteDir="L2res" --cfg=../L2res_cfg.py --unitsPerJob=2 --production_label="V8" -o mc QCD_Pt170to300
python launch.py --remoteDir="L2res" --cfg=../L2res_cfg.py --unitsPerJob=2 --production_label="V8" -o mc QCD_Pt170to300_ext
python launch.py --remoteDir="L2res" --cfg=../L2res_cfg.py --unitsPerJob=2 --production_label="V8" -o mc QCD_Pt300to470
python launch.py --remoteDir="L2res" --cfg=../L2res_cfg.py --unitsPerJob=2 --production_label="V8" -o mc QCD_Pt300to470_ext
python launch.py --remoteDir="L2res" --cfg=../L2res_cfg.py --unitsPerJob=2 --production_label="V8" -o mc QCD_Pt470to600
python launch.py --remoteDir="L2res" --cfg=../L2res_cfg.py --unitsPerJob=2 --production_label="V8" -o mc QCD_Pt600to800
python launch.py --remoteDir="L2res" --cfg=../L2res_cfg.py --unitsPerJob=2 --production_label="V8" -o mc QCD_Pt600to800_ext
python launch.py --remoteDir="L2res" --cfg=../L2res_cfg.py --unitsPerJob=2 --production_label="V8" -o mc QCD_Pt800to1000
python launch.py --remoteDir="L2res" --cfg=../L2res_cfg.py --unitsPerJob=2 --production_label="V8" -o mc QCD_Pt800to1000_ext
python launch.py --remoteDir="L2res" --cfg=../L2res_cfg.py --unitsPerJob=2 --production_label="V8" -o mc QCD_Pt1000to1400
python launch.py --remoteDir="L2res" --cfg=../L2res_cfg.py --unitsPerJob=2 --production_label="V8" -o mc QCD_Pt1000to1400_ext
python launch.py --remoteDir="L2res" --cfg=../L2res_cfg.py --unitsPerJob=2 --production_label="V8" -o mc QCD_Pt1400to1800
python launch.py --remoteDir="L2res" --cfg=../L2res_cfg.py --unitsPerJob=2 --production_label="V8" -o mc QCD_Pt1400to1800_ext
python launch.py --remoteDir="L2res" --cfg=../L2res_cfg.py --unitsPerJob=2 --production_label="V8" -o mc QCD_Pt1800to2400
python launch.py --remoteDir="L2res" --cfg=../L2res_cfg.py --unitsPerJob=2 --production_label="V8" -o mc QCD_Pt1800to2400_ext
python launch.py --remoteDir="L2res" --cfg=../L2res_cfg.py --unitsPerJob=2 --production_label="V8" -o mc QCD_Pt2400to3200
python launch.py --remoteDir="L2res" --cfg=../L2res_cfg.py --unitsPerJob=2 --production_label="V8" -o mc QCD_Pt2400to3200_ext
python launch.py --remoteDir="L2res" --cfg=../L2res_cfg.py --unitsPerJob=2 --production_label="V8" -o mc QCD_Pt3200toInf
